[package]
name = "edr_opt"
version = "0.3.5"
edition = "2021"

[dependencies]
edr_eth = { version = "0.3.5", path = "../edr_eth" }
revm-primitives = { git = "https://github.com/Wodann/revm", rev = "451f122", version = "3.1", default-features = false, features = ["c-kzg", "hashbrown", "optimism", "rand", "serde", "std"] }
