[package]
name = "edr_solidity"
version = "0.3.5"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", default-features = false }
alloy-dyn-abi = { version = "0.7.6", default-features = false }
alloy-json-abi = { version = "0.7.4", default-features = false }
edr_eth = { version = "0.3.5", path = "../edr_eth" }
edr_evm = { version = "0.3.5", path = "../edr_evm" }
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1.0.158", default-features = false, features = ["std"] }
serde_json = { version = "1.0.89", features = ["preserve_order"] }
strum = { version = "0.26.0", features = ["derive"] }

napi = { version = "2.16.0", default-features = false, optional = true }
napi-derive = { version = "2.16.0", default-features = false, optional = true }

[features]
default = []
napi = ["dep:napi", "dep:napi-derive"]

[lints]
workspace = true
